import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider, UserEmailProvider } from "./providers";
import ClientOnly from "./components/ClientOnly";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "G2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="__variable_5cfdac __variable_9a8899 antialiased">
        <ClientOnly>
          <ReactQueryProvider>
            <UserEmailProvider>
              {children}
            </UserEmailProvider>
          </ReactQueryProvider>
        </ClientOnly>
      </body>
    </html>
  );
}
