import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider, UserEmailProvider } from "./providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "G2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body 
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ReactQueryProvider>
          <UserEmailProvider>
            {children}
          </UserEmailProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
